apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spring-app-ingress
  namespace: spring
spec:
  tls:
  - secretName: is-cert
  rules:
  - host: spring.demo.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: spring-app-service
          servicePort: 9000
